### ISSUE TITLE
Remove unconfinement from LXD profile

### ISSUE THREAD

**Issue by johnsca** [canonical/github-runner-operator#13]
The privileged and unconfined parts of the LXD profile (below) are causing issues with the microstack provider. I believe it was originally put in place because it was needed for running CK under LXD. The profile CK used was subsequently changed to drop its privilege requirements making it unnecessary here, but then that caused issues in CK and had to be reverted there. If #12 is done first, we could just move CK deployments to VMs instead and generally speaking, having the LXD profile be unconfined is a significant security risk.

```yaml
security.privileged: "true"
raw.lxc: "lxc.apparmor.profile=unconfined"
```

**Comment by gtrkiller** [comment]
Hello there, I have been reading the code a little bit and it seems that the lxd unconfined option is already commented and the tests reflect it's non-existence. Is there a reason for this issue to be open anyway? Thank you!

**Comment by cbartz** [comment]
Agreeing with https://github.com/canonical/github-runner-operator/issues/13#issuecomment-1138536526 and closing.
