### ISSUE TITLE
Add support for GH job completion / autoscaling webhook

### ISSUE THREAD

**Issue by johnsca** [canonical/github-runner-operator#14]
https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/

The ephemeral runner flow is now officially supported and with that they added [a webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job) to be notified when a workflow job is requested or changes state. This means that instead of the complicated polling logic that we currently have, we could just use the webhook to be told when the runner is done and needs to be replaced.

It also, of course, allows for runners to be spun up or scaled out on demand, if desired, based on the load, which could make for more efficient use of resources.

The one caveat with this is that, since it's a webhook endpoint, that will need to be exposed so that GitHub can connect to it, where the current implementation only requires outbound access from the runners to GH.

**Comment by ijansky** [comment]
I believe that autoscaling could be achieved by [LXD Events](https://linuxcontainers.org/lxd/docs/master/events/) as well. Given that containers shut down after a job gets executed, listening for one of the `instance-shutdown`, `instance-stoped`, or `instance-deleted` events could result in a new instance being spawned. All that without opening any firewall ports.

**Comment by cbartz** [comment]
This is already work in progress ("reactive mode"), and a first simple solution is implemented.
