### ISSUE TITLE
`yq` binary is downloaded without checking the binary signature

### ISSUE THREAD

**Issue by gregory-schiano** [canonical/github-runner-operator#142]
### Bug Description

When `yq` is installed the charm doesn't check the checksum of the downloaded file

### To Reproduce

See
https://github.com/canonical/github-runner-operator/blob/main/src/runner.py#L500-L507

### Environment

Any

### Relevant log output

```shell
N/A
```

**Comment by yhaliaw** [comment]
Started a WIP PR for this issue: https://github.com/canonical/github-runner-operator/pull/143

**Comment by yhaliaw** [comment]
This was fixed in https://github.com/canonical/github-runner-operator/pull/149
