### ISSUE TITLE
GitHub Action fails with error "issues is not supported yet"

### ISSUE THREAD

**Issue by pieqq** [canonical/github-runner-operator#145]
### Bug Description

We use [the following GitHub Action](https://github.com/canonical/checkbox/blob/main/.github/workflows/issues_to_jira.yaml) to create Jira cards when a new issue is raised in our GitHub project. 2 weeks ago, this action [started to fail](https://github.com/canonical/checkbox/actions/workflows/issues_to_jira.yaml) with the following output:

```
<13>Oct 27 01:26:02 ubuntu: GITHUB_EVENT_NAME: issues,   GITHUB_REPOSITORY: canonical/checkbox,   GITHUB_SHA: 710581418d25a5beaeb7ab85cef3bd9975028c4c
<11>Oct 27 01:26:02 ubuntu: issues is not supported yet. Please request it to be added on https://github.com/canonical/github-runner-operator/issues/new/choose
logger: file repo_check_output.txt: No such file or directory
<11>Oct 27 01:26:02 ubuntu: Stopping execution of jobs due to repository setup is not compliant with policies.
<11>Oct 27 01:26:02 ubuntu: This runner will be stopped or lost, please fix the setup of the repository, then rerun this job.
```

Since the error message states to request support for "issues" to be added here, here I am :)

### To Reproduce

1. Create an issue in the Checkbox project

This will trigger the "Issue to Jira" action.

Expected outcome: action passes and a Jira card is created.

Actual outcome: action fails and no Jira cards are created.

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by cbartz** [comment]
@pieqq This will soon be deployed on our infrastructure.
