### ISSUE TITLE
OOM after charmcraft pack

### ISSUE THREAD

**Issue by jneo8** [canonical/github-runner-operator#177]
### Bug Description

The memory usage of the runner unit appears to be very high after we run charmcraft pack in the runner's LXD VM, often exceeding 20GiB. This high usage persists even after manually destroying the LXC container for charmcraft. As a result, we are compelled to use a runner with a much higher memory specification for functional testing.

Upon investigation, I believe the cause is our use of a ramdisk mounted at the root directory of the LXD VM. Consequently, all files downloaded within the VM contribute to an increase in the unit's memory usage.

I am considering whether it's feasible to provide a configuration option to disable the ramdisk. Alternatively, are there any best practices we should follow to run functional tests for the charm project more efficiently?

### To Reproduce

(In lxd runner vm)

```sh
git clone https://github.com/canonical/charm-logrotated.git
charmcraft pack
```

### Environment

Deploy on openstack cloud with

```
juju deploy github-runner --constraints="cores=12 mem=64G" --config token=${token} --config path=${path} --config virtual-machines=1 --config vm-memory=32GiB --config vm-disk=100GiB --config vm-cpu=8 --channel latest/edge

### Relevant log output

```shell
ubuntu@juju-aa3fcc-runner-pool-5:~$ ps aux --sort -%mem | head -n 5
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
lxd        13615  104 18.3 34851500 12076984 ?   Sl   08:39  25:23 /snap/lxd/26200/bin/qemu-system-x86_64 -S -name runner-charm-juju-backup-all-1-e206044105465968fc19c945 -uuid 92f16368-cc35-4bba-a9c1-05d375bd06b5 -daemonize -cpu host,hv_passthrough -nographic -serial chardev:console -nodefaults -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=allow,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/runner-charm-juju-backup-all-1-e206044105465968fc19c945/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/runner-charm-juju-backup-all-1-e206044105465968fc19c945/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/runner-charm-juju-backup-all-1-e206044105465968fc19c945/qemu.pid -D /var/snap/lxd/common/lxd/logs/runner-charm-juju-backup-all-1-e206044105465968fc19c945/qemu.log -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd
```

### Additional context

related: https://github.com/canonical/github-runner-operator/pull/69

**Comment by jdkandersson** [comment]
Thanks for the bug report, this should be resolved soon and it will be possible to mount a volume instead of using RAM disk

**Comment by jneo8** [comment]
After this PR merged. This issue can be closed.

https://github.com/canonical/github-runner-operator/pull/211
