### ISSUE TITLE
Add configuration for juju clouds

### ISSUE THREAD

**Issue by chris-sanders** [canonical/github-runner-operator#3]
The runner needs to support a configuration option to configure Juju clouds.

The intention is to enable the use of juju with test runs utilizing https://github.com/charmed-kubernetes/actions-operator to run tests. While the action can configure LXD and MicroK8s based installs, it would also be desirable for a runner to have clouds configured that the tests can use as well. These could allow tests to access pre-conrigured environments like public clouds and private clouds like OpenStack.

**Comment by cbartz** [comment]
If I understand correctly, this can already be done by the user through appropriate workflow configuration, if the infrastructure allows access to the respective cloud. I do not think the charm should expose any other configuration (cc @jdkandersson @yanksyoon @yhaliaw ). Closing the issue now.
