### ISSUE TITLE
Remove race condition between removing runner and GitHub assigning work to the runner.

### ISSUE THREAD

**Issue by yhaliaw** [canonical/github-runner-operator#31]
### Enhancement Proposal

This can only happen when the number of runner is reduced via configuration, so this should be rare.

The way to resolve this will involve the GitHub runner binary having an atomic operation that checking if the runner is currently busy and remove/unregister from GitHub if not busy.

There is two way to remove/unregister a runner, one method is executing the runner binary, the other is calling a RESTful API on GitHub. From the [documentation](https://docs.github.com/en/actions/hosting-your-own-runners/removing-self-hosted-runners#removing-a-runner-from-a-repository) is it unclear how these two method interacts with the runner being busy.

**Comment by cbartz** [comment]
I think this is issue is no longer valid, can you check @yhaliaw and close, please?
