### ISSUE TITLE
Concurrency in managing the runners

### ISSUE THREAD

**Issue by yhaliaw** [canonical/github-runner-operator#32]
### Enhancement Proposal

As a user, I would like the charm to reconcile the current state and the intended state as soon as possible.

Adding concurrency to the management of the runners would achieve this.

Async would be a good way to add concurrency, as the charm calls external API.
Parallelism might possibly help.

The creation and deletion of runners might benefit from this.

**Comment by cbartz** [comment]
This is already done for runners on openstack cloud, but missing for LXD. The charm will be refactored soon anyway. Still keeping the issue open to keep track (for LXD).

**Comment by cbartz** [comment]
@jdkandersson It seems we are no longer developing new features for LXD, so closing this issue.
