### ISSUE TITLE
Resolve pylxd ws4py problems

### ISSUE THREAD

**Issue by yhaliaw** [canonical/github-runner-operator#34]
### Enhancement Proposal

Due to some problem with ws4py in pylxd sometimes raises broken pipe error, some pylxd functions are replaced with `subprocess.run`.

E.g.,
`instance.exec` of `pylxd` is frequency error out with `BrokenPipeError`. Using `subprocess.run` as workaround for now.

Resolve the issue with pylxd and convert back to using pylxd.

**Comment by cbartz** [comment]
@yhaliaw Can you create a ticket in the backlog or close this issue, please?
