### ISSUE TITLE
Automate runner access based on security policy requirements

### ISSUE THREAD

**Issue by jdkandersson** [canonical/github-runner-operator#41]
Find a way to automate whether runners are available to a given public repository based on compliance with a security policy. Options to consider:
* When a repository requests a runner, check compliance of that repository and refuse to run in case of non-compliance
* Automatically add or remove repositories in an organisation based on whether they comply with security policies

**Comment by cbartz** [comment]
I think this is no longer necessary, can you check @jdkandersson and close the issue, please?
