### ISSUE TITLE
cannot access 10.x network on GH runners

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/github-runner-operator#55]
### Bug Description

Hello,
once machine is deployed, we deploy a workload that opens a gateway on 10.x network.
Unfortunately, we cannot reach it due to some configuration on machine side

we get redirected to the following page:
![image](https://user-images.githubusercontent.com/51964909/233798125-75543451-85c4-459e-9e0d-d0a2c71dc2de.png)

https://github.com/canonical/bundle-kubeflow/actions/runs/4773462457/jobs/8486546553

see Run Connectivity Check

### To Reproduce

-

### Environment

-

### Relevant log output

```shell
-
```

### Additional context

-

**Comment by mthaddon** [comment]
I don't think this is a charm bug, I think we just need to configure `.nip.io` as part of the `juju-no-proxy` variable for the environment where this job is running. I'll leave this issue open until we confirm that.

**Comment by beliaev-maksim** [comment]
@mthaddon do we have this option exposed?
Last time the issue with proxy way resolved by core dns
