### ISSUE TITLE
Consider to add `apt clean` after `apt install` (to release a bit of space of `large` runners)

### ISSUE THREAD

**Issue by taurus-forever** [canonical/github-runner-operator#98]
### Enhancement Proposal

Hi,

The `apt clean` will release 250Mb+ for disk space (docker.io+npm has long list of apt dependencies):
```
Need to get 74.0 MB of archives. = docker.io
Need to get 167 MB of archives.  = npm
Need to get 14.9 MB of archives. = python3-pip
```
Please consider to add `apt clean` here  https://github.com/canonical/github-runner-operator/blob/main/src/runner.py#L651 (after `apt install`).

At the moment `large` runners have 15G only, and 3.4G used out of the box.
Empty 22.04 is 1.5G, +500M Docker, +500M npm, +250M apt cache, + ??? = 3.4G 0_o (we are still searching for 1G of something shipped by [default](https://github.com/canonical/mysql-operator/actions/runs/5822522483/job/15792679690#step:3:6)):
```
> Run df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        15G  3.4G   12G  24% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           1.6G  628K  1.6G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            50M   14M   37M  27% /run/lxd_agent
/dev/sda15      105M  6.1M   99M   6% /boot/efi
```
P.S. do we need to ship npm by default? e.g. Data Platform does not need npm, it is 0.5G of disk usage.
Tnx!

**Comment by beliaev-maksim** [comment]
or we just increase the size of the runners +5GB instead of removing npm

**Comment by taurus-forever** [comment]
Sold. Do not remove npm (if it is necessary).

I am voting to increase `large` VM disk size to 30GB (to match GH runners).

Still I believe we should clean garbage:
 * apt archive: this ticket
 * snap archive: WIP [here](https://chat.charmhub.io/charmhub/pl/s6xn6x9k47rf78u6soc7wo81ga).
 *  .... ?

**Comment by jdkandersson** [comment]
The disk size has been increased now, I'll close this ticket
